[package]
name = "key_gen_bitcoin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "8.2.0"
secp256k1 = {version = "0.27.0", features = ["rand", "bitcoin-hashes"]}
rand = "0.8.5"
